service: api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: api
          method: post
          integration: lambda
          cors: true
#          request:
#            template:
#              application/json: '{ "site": $input.json("$.application") }'
